language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sdcc libudev-dev
  - git clone https://github.com/libusb/libusb.git; cd libusb; ./autogen.sh; ./configure; make; sudo make install
script:
  - "make all"
