language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libudev-dev libboost-all-dev
  - cd ..; wget 'http://freefr.dl.sourceforge.net/project/sdcc/sdcc/3.5.0/sdcc-src-3.5.0.tar.bz2' -O sdcc.tar.bz2; tar xjf sdcc.tar.bz2; cd sdcc-3.5.0; ./configure --disable-pic14-port --disable-pic16-port; make; sudo make install; cd ..; cd cypress-ezusb
  - cd ..; git clone https://github.com/libusb/libusb.git; cd libusb; ./autogen.sh; ./configure; make; sudo make install; cd ..; cd cypress-ezusb

script:
  - "make all"
