language: c

before_install:
  - git clone https://github.com/libusb/libusb.git; cd libusb; ./configure; make; sudo make install
  - sudo apt-get update -qq
  - sudo apt-get install -qq sdcc

script:
  - "make all"
